### ISSUE TITLE
Misspelled title in README

### ISSUE THREAD

**Issue by salfaris** [im-o/mvvm-simplified-coding#3]
I don't want to make a PR for this because it seems trivial and can be misjudged as spam. However, I think that it is worth pointing out that the current title in the README:

_Learn Android Login/Signup with MVVM Paattern_,

is misspelled. In particular, the word **Paattern** should be spelled **Pattern**.

Cheers.

**Comment by im-o** [comment]
@salfaris thankyou bro 😅🥂

**Comment by salfaris** [comment]
You're welcome!
